### ISSUE TITLE
OS in metadata?

### ISSUE THREAD

**Issue by trevorhardy** [GMLC-TDC/helics_benchmark_results#3]
@phlptp and/or @nightlark, when I look at the header information in the benchmark results files, I don't see an explicit indication of the OS. The closest I can find is in the compiler information (assuming we're not cross-compiling) with the generic "Unix"/"Linux" and "Windows". Is there more specific information in there that I'm missing? For example, in the string "Visual Studio 15 2017 x64 Windows-10.0.16299:MSVC-19.12.25835.0" is it safe to say this was run on Windows 10? Is there any more specific information about the flavor of Linux?

**Comment by phlptp** [comment]
That string is 
```
set(HELICS_COMPILER_VERSION "${CMAKE_GENERATOR} ${CMAKE_GENERATOR_PLATFORM} ${CMAKE_SYSTEM}:${CMAKE_CXX_COMPILER_ID}-${CMAKE_CXX_COMPILER_VERSION}")
```

`CMAKE_GENERATOR_PLATFORM` may or may not be there depending on the GENERATOR.  

For
Visual Studio 15 2017 x64 Windows-10.0.16299:MSVC-19.12.25835.0

GENERATOR=Visual Studio 15 2017
PLATFORM=x64
SYSTEM=Windows-10.0.16299
COMPILER=MSVC
VERSION=19.12.25835.0

FOR `Ninja  Linux-4.15.0-65-generic:GNU-7.4.0`

GENERATOR=Ninja
PLATFORM=''
SYSTEM=Linux-4.15.0-65
COMPILER=GNU
VERSION=7.4.0

FOR WSL example `Unix Makefiles  Linux-4.4.0-17763-Microsoft:Clang-6.0.0`
GENERATOR=Unix Makefiles
PLATFORM=''
SYSTEM=Linux-4.4.0-17763-Microsoft
COMPILER=Clang
VERSION=6.0.0

Does this help?

For Linux, the kernel is specified,  not the linux version like (ubuntu or RHEL)  though I am guessing it would be possible to infer from the exact kernel version since they are likely customized somewhat.

**Comment by trevorhardy** [comment]
@phlptp that's quite helpful. I'll work on parsing the complier string to parcel out these pieces of metadata.

**Comment by trevorhardy** [comment]
@phlptp is the Linux kernel (for our purposes) everything after "Linux" to the ":" or is it just the version string between the "-"es? In the last example above (```Linux-4.4.0-17763-Microsoft```) the difference would be:

```4.4.0-17763-Microsoft```
vs.
```4.4.0```

**Comment by phlptp** [comment]
I suppose it kind of depends on what we want to do with it.  The CMAKE_SYSTEM is everything to the ':' 
The difference between the first one is running in WSL, which might be a pretty big distinction, even if it is the same Kernel.

**Comment by trevorhardy** [comment]
OK; I'm going to split up that string into metadata chunks in case we need it in the future.

**Comment by phlptp** [comment]
Can you check the 12-05 results those should have updated some of the things you mentioned.  If further changes are needed from the format in those files, that would be a point to discuss more.

**Comment by trevorhardy** [comment]
What things are you referring to, @phlptp? I did the compiler parsing already and have committed that code up. I was about to close out this task when I saw your comment.

**Comment by phlptp** [comment]
That was in response to your email.  I thought it was connected with this issue.

**Comment by trevorhardy** [comment]
Got it. This issue is more specific. The email I just sent was about some naming inconsistencies. I'll look at the 12-05 data.
